# Generated by Django 3.2.13 on 2023-05-01 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название доп.услуги')),
                ('image', models.ImageField(upload_to='images/add/', verbose_name='изображение услуги')),
            ],
            options={
                'verbose_name': 'Доп.услуга',
                'verbose_name_plural': 'Доп.услуги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Name_Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название организации')),
            ],
            options={
                'verbose_name': 'Название организации',
                'verbose_name_plural': 'Названия организации',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование изображения')),
                ('image', models.ImageField(upload_to='images/Фото', verbose_name='изображение для ценника')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='images/price', verbose_name='изображение для ценника')),
                ('name', models.CharField(max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Название вида работы')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название проекта')),
                ('content', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('photo1', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='изображение 1')),
                ('photo2', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='изображение 2')),
                ('photo3', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='изображение 3')),
                ('photo4', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='изображение 4')),
                ('photo5', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='изображение 5')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='News_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('content', models.TextField(blank=True, verbose_name='контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('photo', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='изображения')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at', 'title', 'id'],
            },
        ),
    ]
