# Generated by Django 3.2.13 on 2023-05-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additional_services',
            options={'ordering': ['title'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterField(
            model_name='additional_services',
            name='image',
            field=models.ImageField(upload_to='images/Фото/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='additional_services',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наименование фотографий'),
        ),
    ]
